import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import { S3Client, PutObjectCommand, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import PDFDocument from "pdfkit";
import { Readable } from "stream";

// ── Clients ───────────────────────────────────────────────────────────────────

const dynamo = DynamoDBDocumentClient.from(
  new DynamoDBClient({ region: process.env.AWS_REGION || "eu-west-1" }),
  { marshallOptions: { removeUndefinedValues: true } }
);
const s3 = new S3Client({ region: process.env.S3_REGION || process.env.AWS_REGION || "eu-west-1" });

const REPORTS_TABLE = process.env.REPORTS_TABLE;
const S3_BUCKET     = process.env.S3_BUCKET_REPORTS;

// ── CORS Headers ──────────────────────────────────────────────────────────────

const CORS_HEADERS = {
  "Access-Control-Allow-Origin":  "*",
  "Access-Control-Allow-Headers": "Content-Type,Authorization",
  "Access-Control-Allow-Methods": "POST,OPTIONS",
  "Content-Type": "application/json",
};

const response = (statusCode, body) => ({
  statusCode,
  headers: CORS_HEADERS,
  body: JSON.stringify(body),
});

// ── PDF generation ────────────────────────────────────────────────────────────

const streamToBuffer = (stream) =>
  new Promise((resolve, reject) => {
    const chunks = [];
    stream.on("data", (d) => chunks.push(d));
    stream.on("end",  ()  => resolve(Buffer.concat(chunks)));
    stream.on("error", reject);
  });

const generatePdfBuffer = async (report) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  // Header
  doc.fontSize(22).font("Helvetica-Bold").text("Career Assessment Report", { align: "center" });
  doc.moveDown(0.3);
  doc.fontSize(11).font("Helvetica").fillColor("#6B7280")
    .text(`Generated: ${new Date(report.generatedAt).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, { align: "center" });
  doc.moveDown(1);

  // Stream Recommendation
  if (report.streamRecommendation) {
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#4F46E5").text("Recommended Stream");
    doc.fontSize(18).font("Helvetica-Bold").fillColor("#111827").text(report.streamRecommendation);
    if (report.streamJustification) {
      doc.fontSize(11).font("Helvetica").fillColor("#374151").text(report.streamJustification);
    }
    doc.moveDown(1);
  }

  // Career Matches
  if (report.careerMatches?.length) {
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Top Career Matches");
    doc.moveDown(0.4);
    report.careerMatches.slice(0, 10).forEach((c, i) => {
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#111827")
        .text(`${i + 1}. ${c.career}  (${c.matchScore}% match)`);
      if (c.description) {
        doc.fontSize(10).font("Helvetica").fillColor("#6B7280").text(c.description, { indent: 16 });
      }
      doc.moveDown(0.3);
    });
    doc.moveDown(0.5);
  }

  // Personality Profile
  const personality = report.personalityProfile || {};
  if (personality.summary) {
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Personality Profile");
    doc.fontSize(11).font("Helvetica").fillColor("#374151").text(personality.summary);
    doc.moveDown(0.8);
  }

  // Strengths
  if (report.strengthsSummary) {
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Your Strengths");
    doc.fontSize(11).font("Helvetica").fillColor("#374151").text(report.strengthsSummary);
    doc.moveDown(0.8);
  }

  // Roadmap
  if (report.roadmap?.length) {
    doc.addPage();
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#111827").text("Your Career Roadmap");
    doc.moveDown(0.5);
    report.roadmap.forEach((step, i) => {
      doc.fontSize(11).font("Helvetica-Bold").fillColor("#7C3AED").text(step.timeframe || `Step ${i + 1}`);
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#111827").text(step.milestone);
      if (step.description) {
        doc.fontSize(10).font("Helvetica").fillColor("#6B7280").text(step.description);
      }
      doc.moveDown(0.5);
    });
  }

  // Footer
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(9).font("Helvetica").fillColor("#9CA3AF")
      .text("Generated by ChillCareer · AI-Powered Career Guidance", 50, doc.page.height - 40, { align: "center" });
  }

  doc.end();
  return streamToBuffer(doc);
};

// ── Handler ───────────────────────────────────────────────────────────────────

export const handler = async (event) => {
  console.log("Event:", JSON.stringify(event, null, 2));

  try {
    let body;
    try {
      body = JSON.parse(event.body || "{}");
    } catch {
      return response(400, { success: false, error: "Invalid JSON body" });
    }

    const { userId, reportId } = body;
    if (!userId || !reportId) {
      return response(400, { success: false, error: "userId and reportId are required" });
    }

    // ── Fetch report ──────────────────────────────────────────────────────────
    const reportRes = await dynamo.send(new GetCommand({ TableName: REPORTS_TABLE, Key: { reportId } }));
    const report    = reportRes.Item;

    if (!report || report.userId !== userId) {
      return response(404, { success: false, error: "Report not found" });
    }
    if (!report.paymentDone) {
      return response(403, { success: false, error: "Payment required to download PDF" });
    }

    // ── Return existing pdfUrl if already generated ───────────────────────────
    if (report.pdfUrl) {
      return response(200, { success: true, data: { pdfUrl: report.pdfUrl } });
    }

    // ── Generate PDF ──────────────────────────────────────────────────────────
    const pdfBuffer = await generatePdfBuffer(report);

    // ── Upload to S3 ──────────────────────────────────────────────────────────
    const s3Key = `pdfs/${userId}/${reportId}.pdf`;
    await s3.send(new PutObjectCommand({
      Bucket:      S3_BUCKET,
      Key:         s3Key,
      Body:        pdfBuffer,
      ContentType: "application/pdf",
    }));
    console.log("PDF uploaded to S3:", s3Key);

    // ── Generate presigned URL (valid 24h) ────────────────────────────────────
    const pdfUrl = await getSignedUrl(
      s3,
      new GetObjectCommand({ Bucket: S3_BUCKET, Key: s3Key }),
      { expiresIn: 86400 }
    );

    // ── Save pdfUrl back to report ────────────────────────────────────────────
    await dynamo.send(new UpdateCommand({
      TableName:                 REPORTS_TABLE,
      Key:                       { reportId },
      UpdateExpression:          "SET pdfUrl = :url",
      ExpressionAttributeValues: { ":url": pdfUrl },
    }));

    return response(200, { success: true, data: { pdfUrl } });

  } catch (error) {
    console.error("Error generating PDF:", error);
    return response(500, { success: false, error: "Failed to generate PDF" });
  }
};
